version: '2'

services:

    # APP

    nginx:
        build: docker/nginx
        volumes:
            - "./:/symfony"
        links:
            - php
        ports:
            - "80:80" # change host port depending on your needs

    php:
        build: docker/php
        volumes:
            - "./:/symfony"
        links:
            - mysql
            - maildev

    mysql:
        build: docker/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_USER=symfony"
            - "MYSQL_PASSWORD=symfony"
            - "MYSQL_DATABASE=symfony"
        ports:
            - "3306:3306" # comment or change host port depending on your needs

    # DEV TOOLS

    maildev:
        image: djfarrelly/maildev
        ports:
            - "1080:80"

#    phpmyadmin:
#        image: phpmyadmin/phpmyadmin:4.6
#        environment:
#            - "MYSQL_ROOT_PASSWORD=root"
#            - "MYSQL_USER=symfony"
#            - "MYSQL_PASSWORD=symfony"
#        links:
#            - mysql:db
#        ports:
#            - "8080:80"
